Repository civicrm/civicrm-backdrop, pull requests merged in 2019-04, with the labels that each got.

#69 Fix up to newer coder style
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  tests/phpunit/CiviBackdrop/HookTest.php
Labels: 1.x-5.13

#70 1.x 5.13
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  tests/phpunit/CiviBackdrop/HookTest.php
Labels: 1.x-master

#72 (NFC) Update for compliance with next phpcs standard
  civicrm.install
  civicrm.module
  modules/civicrm_contact_ref/civicrm_contact_ref.module
  modules/civicrm_group_roles/civicrm_group_roles.module
  modules/civicrm_member_roles/civicrm_member_roles.module
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrmtheme/civicrmtheme.module
Labels: 1.x-5.13

#73 1.x 5.13
  civicrm.install
  civicrm.module
  modules/civicrm_contact_ref/civicrm_contact_ref.module
  modules/civicrm_group_roles/civicrm_group_roles.module
  modules/civicrm_member_roles/civicrm_member_roles.module
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrmtheme/civicrmtheme.module
Labels: 1.x-master, merge on pass

#74 #68: Allow formatting created date in Views
  modules/views/components/civicrm.core.inc
Labels: 1.x-master

#76 Issue 75
  civicrm.module
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_group_roles/civicrm_group_roles.module
  modules/civicrm_member_roles/civicrm_member_roles.module
  modules/views/civicrm/civicrm_handler_field_activity.inc
  modules/views/civicrm/civicrm_handler_field_country.inc
  modules/views/civicrm/civicrm_handler_field_county.inc
  modules/views/civicrm/civicrm_handler_field_encounter_medium.inc
  modules/views/civicrm/civicrm_handler_field_option.inc
  modules/views/civicrm/civicrm_handler_field_relationship_type.inc
  modules/views/civicrm/civicrm_handler_field_state.inc
  modules/views/civicrm/civicrm_handler_field_website.inc
  modules/views/civicrm/civicrm_handler_filter_encounter_medium.inc
  modules/views/civicrm/civicrm_handler_filter_group_status.inc
  modules/views/civicrm/civicrm_handler_filter_option.inc
  modules/views/civicrm/civicrm_handler_filter_relationship_type.inc
  modules/views/civicrm/civicrm_handler_relationship_im.inc
  modules/views/civicrm/civicrm_handler_relationship_participant.inc
  modules/views/civicrm/civicrm_handler_relationship_phone.inc
  modules/views/civicrm/civicrm_handler_relationship_website.inc
  modules/views/components/civicrm.core.inc
Labels: 1.x-master

#77 Issue 64: use new field type = number
  modules/civicrm_member_roles/civicrm_member_roles.module
  modules/views/civicrm/civicrm_handler_field_contact_image.inc
Labels: 1.x-master

#78 Port fix for dev/drupal#48 to fix column name for next_sched_contribu…
  modules/views/components/civicrm.contribute.inc
Labels: 1.x-master

#79 Bump Minimum PHP Version to match what is required as per core install
  civicrm.info
Labels: 1.x-master, merge on pass
