Repository civicrm/civicrm-backdrop, pull requests merged in 2019-08, with the labels that each got.

#92 Civicrmtheme enabled when drush install [issue #90]
  drush/civicrm.drush.inc
Labels: 1.x-master

#93 issue #89 degault user permissions are now set when using drush install
  drush/civicrm.drush.inc
Labels: 1.x-master

#87 Issue 86: Fixed errors when load_generated_data=true civicrm-install
  drush/civicrm.drush.inc
Labels: 1.x-master

#96 updated bootstrap constant name to match that in BackdropBoot
  drush/civicrm.drush.inc
Labels: 1.x-master

#99 (NFC) civicrm.drush.inc - Cleanup style
  drush/civicrm.drush.inc
Labels: 1.x-master

#98 Fail more gracefully when upgrading on PHP5.x
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviBackdrop/PHPVersionTest.php
Labels: 1.x-5.17

#100 Fail more gracefully when upgrading on PHP5.x
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviBackdrop/PHPVersionTest.php
Labels: 1.x-5.16
