Repository civicrm/civicrm-backdrop, pull requests merged in 2019-11, with the labels that each got.

#102 Update copyright date for 2020
  civicrm.install
  civicrm.module
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Form/Inline/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Page/Inline/Demographics.tpl
  modules/civicrm_rules/civicrm_rules.contact-eval.inc
  modules/civicrm_rules/civicrm_rules.event-eval.inc
  modules/civicrm_rules/civicrm_rules.install
  modules/civicrm_rules/civicrm_rules.mailing-eval.inc
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.participant-eval.inc
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_action.inc
  modules/civicrm_rules/civicrm_rules_condition.inc
  modules/civicrm_rules/civicrm_rules_entity.inc
  modules/civicrm_rules/civicrm_rules_event.inc
  modules/civicrm_rules/civicrm_rules_utils.inc
  modules/civicrmtheme/civicrmtheme.install
  modules/civicrmtheme/civicrmtheme.module
Labels: 1.x-master

#103 #84: Backdrop CSS needed on all pages
  civicrm.info
  civicrm_backdrop.css
Labels: 1.x-master

#104 (NFC) (dev/core#878) Simplify copyright header
  civicrm.install
  civicrm.module
  drush/civicrm.drush.inc
  modules/civicrm_engage/Engage/Report/Form/CallList.php
  modules/civicrm_engage/Engage/Report/Form/List.php
  modules/civicrm_engage/Engage/Report/Form/WalkList.php
  modules/civicrm_engage/civicrm_engage.install
  modules/civicrm_engage/civicrm_engage.module
  modules/civicrm_engage/templates/CRM/Contact/Form/Edit/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Form/Inline/Demographics.tpl
  modules/civicrm_engage/templates/CRM/Contact/Page/Inline/Demographics.tpl
  modules/civicrm_engage/templates/Engage/Report/Form/CallList.tpl
  modules/civicrm_rules/civicrm_rules.contact-eval.inc
  modules/civicrm_rules/civicrm_rules.event-eval.inc
  modules/civicrm_rules/civicrm_rules.install
  modules/civicrm_rules/civicrm_rules.mailing-eval.inc
  modules/civicrm_rules/civicrm_rules.module
  modules/civicrm_rules/civicrm_rules.participant-eval.inc
  modules/civicrm_rules/civicrm_rules.rules.inc
  modules/civicrm_rules/civicrm_rules_action.inc
  modules/civicrm_rules/civicrm_rules_condition.inc
  modules/civicrm_rules/civicrm_rules_entity.inc
  modules/civicrm_rules/civicrm_rules_event.inc
  modules/civicrm_rules/civicrm_rules_utils.inc
  modules/civicrmtheme/civicrmtheme.install
  modules/civicrmtheme/civicrmtheme.module
Labels: 1.x-master

#105 1.x 5.17
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviBackdrop/PHPVersionTest.php
Labels: 1.x-5.19

#106 1.x 5.19
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviBackdrop/PHPVersionTest.php
Labels: 1.x-5.20

#107 1.x 5.20
  civicrm.info
  civicrm.module
  drush/civicrm.drush.inc
  tests/phpunit/CiviBackdrop/PHPVersionTest.php
Labels: 1.x-master
